# Generated by Django 5.0.6 on 2024-06-07 23:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundAnimalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('area', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date', models.DateField()),
                ('added', models.CharField(choices=[('Пользователь зарегистрирован', 'YesReg'), ('Пользователь не зарегистрирован', 'NoReg')], max_length=50)),
            ],
        ),
    ]
