# Generated by Django 5.0.6 on 2024-06-09 09:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miss_animals', '0002_remove_foundanimalcard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundanimalcard',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU'),
        ),
    ]
