# Generated by Django 5.0.6 on 2024-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_animals', '0003_alter_foundanimalcard_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundanimalcard',
            name='image',
            field=models.ImageField(default='static/test.jpg', upload_to='images/'),
        ),
    ]
