# Generated by Django 5.0.6 on 2024-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_animals', '0005_alter_foundanimalcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundanimalcard',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='images/75dacb88-2cbc-4984-b644-fd2b96e1c8cb'),
        ),
    ]
