# Generated by Django 5.0.6 on 2024-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_animals', '0009_alter_foundanimalcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundanimalcard',
            name='image',
            field=models.ImageField(default='images/default/test.jpg', upload_to='images/7a99bbde-b974-4e7e-8cc0-e4f04066666e/'),
        ),
    ]
