# Generated by Django 5.0.6 on 2024-06-11 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_animals', '0010_alter_foundanimalcard_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundanimalcard',
            name='image',
            field=models.ImageField(default='images/default/test.jpg', upload_to='images/e32a633e-acbe-4e6a-9595-574fa3148b24/'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='advertisements/')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('moderation', 'На модерации'), ('found', 'Найдено'), ('archive', 'В архиве')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
